/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yTXJMt92km2
 */
'use client'
import Link from "next/link"
import Image from "next/image"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Navbar from "./navbar"

export function HomePage() {
  return (
    <div key="1" className="flex flex-col min-h-screen bg-[#101217ff] text-[#C79026ff] font-pathway-gothic-one">
      <header className="px-4 lg:px-6 h-14 flex items-center justify-between bg-[#5E6D61ff] border-b border-[#8E7E62ff]">
        <div className="flex items-center">
          <Image src="/colorwheel2-removebg-preview.png" width="60" height="60" />
          <h1 className="text-2xl font-bold">Chad Avalon Color</h1>
        </div>
        <Navbar />
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32">
          <div className="container mx-auto px-4 md:px-6">
            <span className="w-full h-auto shadow-lg rounded-md bg-muted" />
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="video-gallery">
          <h2 className="text-3xl font-bold tracking-tighter text-center sm:text-4xl md:text-5xl">Video Gallery</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4">
            <a className="group block aspect-w-16 aspect-h-9 overflow-hidden rounded-lg shadow-lg" href="#">
              <img
                alt="Video thumbnail"
                className="transition-transform group-hover:scale-105"
                height="720"
                layout="fill"
                objectFit="cover"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1280/720",
                  objectFit: "cover",
                }}
                width="1280"
              />
            </a>
            <a className="group block aspect-w-16 aspect-h-9 overflow-hidden rounded-lg shadow-lg" href="#">
              <img
                alt="Video thumbnail"
                className="transition-transform group-hover:scale-105"
                height="720"
                layout="fill"
                objectFit="cover"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1280/720",
                  objectFit: "cover",
                }}
                width="1280"
              />
            </a>
            <a className="group block aspect-w-16 aspect-h-9 overflow-hidden rounded-lg shadow-lg" href="#">
              <img
                alt="Video thumbnail"
                className="transition-transform group-hover:scale-105"
                height="720"
                layout="fill"
                objectFit="cover"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1280/720",
                  objectFit: "cover",
                }}
                width="1280"
              />
            </a>
            <a className="group block aspect-w-16 aspect-h-9 overflow-hidden rounded-lg shadow-lg" href="#">
              <img
                alt="Video thumbnail"
                className="transition-transform group-hover:scale-105"
                height="720"
                layout="fill"
                objectFit="cover"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1280/720",
                  objectFit: "cover",
                }}
                width="1280"
              />
            </a>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#292F2Bff]">
          <h2 className="text-3xl font-bold tracking-tighter text-center sm:text-4xl md:text-5xl">Image Gallery</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4">
            <a className="group block aspect-w-16 aspect-h-9 overflow-hidden rounded-lg shadow-lg" href="#">
              <img
                alt="Image thumbnail"
                className="transition-transform group-hover:scale-105"
                height="720"
                layout="fill"
                objectFit="cover"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1280/720",
                  objectFit: "cover",
                }}
                width="1280"
              />
            </a>
            <a className="group block aspect-w-16 aspect-h-9 overflow-hidden rounded-lg shadow-lg" href="#">
              <img
                alt="Image thumbnail"
                className="transition-transform group-hover:scale-105"
                height="720"
                layout="fill"
                objectFit="cover"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1280/720",
                  objectFit: "cover",
                }}
                width="1280"
              />
            </a>
            <a className="group block aspect-w-16 aspect-h-9 overflow-hidden rounded-lg shadow-lg" href="#">
              <img
                alt="Image thumbnail"
                className="transition-transform group-hover:scale-105"
                height="720"
                layout="fill"
                objectFit="cover"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1280/720",
                  objectFit: "cover",
                }}
                width="1280"
              />
            </a>
            <a className="group block aspect-w-16 aspect-h-9 overflow-hidden rounded-lg shadow-lg" href="#">
              <img
                alt="Image thumbnail"
                className="transition-transform group-hover:scale-105"
                height="720"
                layout="fill"
                objectFit="cover"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1280/720",
                  objectFit: "cover",
                }}
                width="1280"
              />
            </a>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="about">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter text-center sm:text-4xl md:text-5xl">About Me</h2>
            <p className="max-w-prose mx-auto mt-8 text-[#8E7E62ff]">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed purus nunc, ultrices in pharetra non, mollis
              sed nisl. Curabitur auctor nulla id dui vulputate, quis luctus mi lacinia.
            </p>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="contact">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tighter text-center sm:text-4xl md:text-5xl">Contact Me</h2>
            <form className="max-w-md mx-auto mt-8 space-y-4">
              <Input
                className="w-full bg-[#5E6D61ff] text-[#C79026ff] border-[#8E7E62ff]"
                placeholder="Name"
                type="text"
              />
              <Input
                className="w-full bg-[#5E6D61ff] text-[#C79026ff] border-[#8E7E62ff]"
                placeholder="Email"
                type="email"
              />
              <textarea
                className="w-full h-32 resize-none bg-[#5E6D61ff] text-[#C79026ff] border-[#8E7E62ff]"
                placeholder="Message"
              />
              <Button className="w-full bg-[#5E6D61ff] text-[#C79026ff] border-[#8E7E62ff]" type="submit">
                Submit
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="flex justify-center items-center h-14 bg-[#5E6D61ff] border-t border-[#8E7E62ff]">
        <p className="text-xs text-[#755F4Dff]">© 2023 Freelance Film Colorist. All rights reserved.</p>
      </footer>
    </div>
  )
}
